const int MAX_DIRECTIONAL_LIGHTS = 4;
const int MAX_POINT_LIGHTS = 64;
const int MAX_SPOT_LIGHTS = 64;

const int MAX_DIRECTIONAL_LIGHTS_SHADOWS = 4;
const int MAX_POINT_LIGHTS_SHADOWS = 16;
const int MAX_SPOT_LIGHTS_SHADOWS = 32;

const float SHADOWMAP_TEXEL_SIZE = 1.0 / 2048.0;